fix: define django_app_config if django version < 3.2
openedx/completion pull request #259
Opened 2023-10-25 11:25 UTC by DanielVZ96

**Description:** 

Newer django versions throw the following warning: `RemovedInDjango41Warning: 'completion' defines default_app_config = 'completion.apps.CompletionAppConfig'. Django now detects this configuration automatically. You can remove default_app_config.`, and it clutters edx-platform logs. This PR avoids defining it when django.VERSION < 3.2

**Related issue:** https://github.com/openedx/edx-platform/issues/33572

**Installation instructions:** List any non-trivial installation 
instructions.

**Testing instructions:**
- create and activate a virtual environment using python 3.8.17
- run `make install`
- run  `pytest -k "DefaultAppConfig" --no-cov -v`and make sure `test_not_defined` passes and `test_defined` is skipped
- install a django version lower than 3.2
- run  `pytest -k "DefaultAppConfig" --no-cov -v`and make sure `test_not_defined` is skipped and `test_defined` passes

**Reviewers:**
- [ ] tag reviewer 
- [ ] tag reviewer 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

2023-10-25 11:25 UTC, openedx-webhooks commented
Thanks for the pull request, @DanielVZ96!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by adding a comment here that you have signed it.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-10-25 13:22 UTC, mphilbrick211 commented
Hi @DanielVZ96! Thank you for this contribution! Please let me know if you have any questions regarding submitting a [CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base).

Note, if you are not contributing as an individual, and are contributing on behalf of an organization, please let me know as the CLA process is a bit different in that case.

2023-10-26 10:08 UTC, Agrendalath commented on completion/__init__.py
> +    default_app_config = 'completion.apps.CompletionAppConfig'  # pylint: disable=invalid-name
We no longer need to support Django versions older than `3.2`.

2023-10-26 19:27 UTC, e0d commented
@DanielVZ96 
Hi, we need to have a valid Contributor License Agreement (CLA) in place for all contributions.  See the welcome message above for the details about how to enroll.  The process is different depending upon whether you are making this contribution as an individual or on behalf of your employer. 

It also looks like there are some test failures that need attention.

2023-10-26 22:15 UTC, DanielVZ96 commented
Hi @e0d, i'm already in the process to sign it.

2023-10-27 13:59 UTC, Agrendalath requested changes

2023-10-27 13:59 UTC, Agrendalath commented on completion/__init__.py
> +__version__ = '4.4.0'
Please bump the patch version and add an entry to `CHANGELOG.rst `.

2023-10-27 13:59 UTC, Agrendalath commented on completion/__init__.py
> +import django
Is it a leftover from the previous commit? Please only do force-pushes (other than branch rebases) after the end of the review. Doing it earlier makes changes harder to track.

2023-10-27 13:59 UTC, Agrendalath commented on completion/tests/test_compatibility.py
> +        self.assertFalse(hasattr(completion, "default_app_config"))
We don't need a test for this.

2023-10-30 10:23 UTC, Agrendalath approved these changes
:+1:

* [x] I tested this: checked that the warning is gone
* [x] I read through the code
* [x] I checked for accessibility issues: n/a
* [x] Includes documentation: n/a

2023-10-30 10:26 UTC, Agrendalath commented
@pkulkark, would you like to review this as the CC? The only thing needed for testing this is checking that the `RemovedInDjango41Warning` warning is not present in the Tests CI logs (e.g., "django32-drf314").

2023-11-02 14:03 UTC, pkulkark approved these changes
@DanielVZ96 @Agrendalath LGTM :+1:. I verified that there were no `RemovedInDjango41Warning` in any of the CI tests. I did notice a couple of `RemovedInDjango51Warning` like this:
```
/home/runner/work/completion/completion/.tox/django42-drf314/lib/python3.8/site-packages/django/db/models/options.py:210: RemovedInDjango51Warning: 'index_together' is deprecated. Use 'Meta.indexes' in 'completion.BlockCompletion' instead.
```
But I suppose that'll be tackled when we upgrade to django 5.

2023-11-03 13:56 UTC, merged

2023-11-03 13:56 UTC, openedx-webhooks commented
@DanielVZ96 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/completion&entry.867055334=https://github.com/openedx/completion/pull/259&entry.1484655318=https://github.com/DanielVZ96&entry.752974735=2023-10-25+11:25&entry.1917517419=2023-11-03+13:56&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->